name: Fantacalcio Bot - Salvataggio Automatico Formazione

on:
  schedule:
    # Martedì alle 11:00 UTC = 13:00 ora italiana
    - cron: '0 11 * * 2'
    # Giovedì alle 11:00 UTC = 13:00 ora italiana
    - cron: '0 11 * * 4'
  
  # Permette di eseguire manualmente il workflow
  workflow_dispatch:

jobs:
  salva-formazione:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
    
    - name: 🐍 Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: 🌐 Setup Google Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    
    - name: 🚗 Install ChromeDriver
      uses: nanasess/setup-chromedriver@v2
    
    - name: 📦 Install Python dependencies
      run: |
        echo "Installazione dipendenze Python..."
        pip install --upgrade pip
        pip install selenium
        echo "✅ Dipendenze installate"
    
    - name: ✅ Verifica ambiente
      run: |
        echo "======================================"
        echo "Verifica ambiente di esecuzione"
        echo "======================================"
        echo "Python version:"
        python --version
        echo ""
        echo "Google Chrome:"
        which google-chrome
        google-chrome --version
        echo ""
        echo "ChromeDriver:"
        which chromedriver
        chromedriver --version
        echo "======================================"
    
    - name: 🤖 Esegui Fantacalcio Bot
      id: bot_execution
      env:
        FANTACALCIO_USERNAME: ${{ secrets.FANTACALCIO_USERNAME }}
        FANTACALCIO_PASSWORD: ${{ secrets.FANTACALCIO_PASSWORD }}
        GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        CHROME_BIN: /usr/bin/google-chrome
      run: |
        echo "======================================"
        echo "🤖 AVVIO FANTACALCIO BOT"
        echo "======================================"
        echo "Lega: Lega Paralimpica Seregno"
        echo "Username: $FANTACALCIO_USERNAME"
        echo "Modalità: Salvataggio formazione attuale"
        echo "Timestamp: $(date '+%Y-%m-%d %H:%M:%S')"
        echo "======================================"
        echo ""
        python fantacalcio_bot.py
        echo ""
        echo "======================================"
        echo "✅ ESECUZIONE COMPLETATA"
        echo "======================================"
    
    - name: 📄 Upload logs e screenshot in caso di errore
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-logs-run-${{ github.run_number }}
        path: |
          fantacalcio_log.txt
          errore_*.png
        retention-days: 7
    
    - name: 📊 Riepilogo esecuzione
      if: always()
      run: |
        echo "=================================================="
        echo "📊 RIEPILOGO ESECUZIONE WORKFLOW"
        echo "=================================================="
        echo "Workflow: ${{ github.workflow }}"
        echo "Run ID: ${{ github.run_id }}"
        echo "Run Number: ${{ github.run_number }}"
        echo "Job Status: ${{ job.status }}"
        echo "Timestamp: $(date '+%Y-%m-%d %H:%M:%S')"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref }}"
        echo "=================================================="
        echo ""
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ Formazione salvata con successo!"
          echo "📧 Email di conferma inviata a saladaniele99@gmail.com"
        else
          echo "❌ Esecuzione fallita"
          echo "📧 Email di errore inviata a saladaniele99@gmail.com"
          echo "📄 Log e screenshot disponibili negli Artifacts"
        fi
        echo "=================================================="
